language: go
sudo: false
go:
    - 1.5
addons:
    apt:
        packages:
            - git-2.0
    

before_install:
    - git --version
    - hg --version

script:
    - go test -v ./... -coverprofile=coverage.txt -covermode=atomic
after_success:
    - bash <(curl -s https://codecov.io/bash)
